channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=23.2.1
- pip:
  - mlflow==3.5.1
  - numpy==2.3.4
  - pandas==2.3.3
  - psutil==7.1.2
  - pyarrow==21.0.0
  - scikit-learn==1.7.2
  - scipy==1.16.3
  - xgboost==3.1.1
name: mlflow-env
